@echo off
set MBG_DATA_DIR=data
if "%MBG_LOCAL_PROFILE%"=="" set MBG_LOCAL_PROFILE=AUTO
if "%MBG_LOCAL_ALL_MODELS%"=="" set MBG_LOCAL_ALL_MODELS=1
echo MBG_LOCAL_PROFILE=%MBG_LOCAL_PROFILE%
echo MBG_LOCAL_ALL_MODELS=%MBG_LOCAL_ALL_MODELS%
jupyter lab notebooks/MBG_LOCAL_ALL_MODELS_V4.ipynb
